apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-myclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 500Mi
